---
title: "Gastro-intestinal transmission and colonisation of pathogenic bacteria: calibration of an agent-based model"
author: "Alessandro Gerada, Conor Rosato, Alex Howard, Peter L Green, William Hope"
date: "2024-03-18"
output:
  word_document: default
  pdf_document: default
---

__Introduction__
Transmission of potentially pathogenic bacteria under antimicrobial selective pressure has important implications for control of hospital-acquired infection. Examples include _Clostridioides difficile_ infection (CDI) and Vancomycin-resistant _Enterococcus_. In addition to patient factors, colonisation risk depends on environmental factors (e.g., surface cleaning), proximity to other colonised patients, and use of antimicrobial agents. To guide infection control strategies, especially during outbreaks, we developed an agent-based simulator and estimated its parameters using data from a CDI outbreak documented by Salgado et al [American Journal of Infection Control 37, 458–464 (2009)].

__Methods__
An agent-based model was implemented using NetLogo -- a virtual hospital was built with a configurable structure (number of wards, beds per ward, number of toilets, etc.). Input parameters included patient factors (e.g., community colonisation rate), population behaviour (e.g., frequency of toilet use), and infection control measures (e.g., toilet cleaning frequency). Risk of infection changed as patients shared use of contaminated toilets, or were prescribed antimicrobial therapy. Rejection sampling approximate Bayesian computation was employed to calibrate the model to the outbreak data. Using cases per 1000 patient days as a summary statistic, simulated data were compared to the actual reported rate of nosocomial CDI. Priors were determined from domain expertise or extracted from existing literature. Firstly, the model was calibrated to pre-outbreak data to identify parameters that simulated the baseline rate. Next, we simulated outbreaks and suppression by incrementally raising colonisation pressure over time (via increased antimicrobial consumption, toilet use, etc.) and enhancing infection control measures, respectively. Finally, the estimated parameter means were used as an input in 56 outbreak random simulations.

__Results__
After calibration, key parameters included: community colonisation rate of 3.8%, rising to 5.7% during the outbreak period; 31.9% patients were administered an antimicrobial during their admission, rising to 45.8% during the outbreak, and reducing to 27.9% after enhancing infection control measures. The rate of patient toilet frequenting rose from a mean of 1.6 to 2.8 times during the outbreak. Simulated data had a pre-outbreak baseline median rate of 0.75 cases per 1000 patient days [interquartile (IQR) range 0--1.66], compared with the real rate of 1.25 cases per 1000 [IQR 0.94--1.56]. During the outbreak period, simulations had a median rate of 4.65 [IQR 2.34--7.65] cases, compared with the real median rate of 3.74 [IQR 3.32--4.41]. 

__Discussion__
Repeated simulations using the model generated nosocomial CDI rates that showed a clear outbreak peak, followed by suppression of colonisation/infection over time, resembling a real hospital CDI outbreak. The interactive nature of the model can be used for outbreak preparedness by testing out different infection control strategies.

__Conclusion__
We report a pathogen-agnostic model that can be used to simulate any infection with features such as faecal-oral transmission, colonisation, and antimicrobial selective pressure effects. 
